# Generated by Django 5.2.6 on 2026-03-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='markdown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
