# Generated by Django 5.2.6 on 2026-03-10 18:15

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
